#ifndef __SIGNALNUM_H__
#define __SIGNALNUM_H__

//输入信号编号
#define InSignalNum_Null		0
#define InSignalNum_MOP			1
#define InSignalNum_MCP			2
#define InSignalNum_DOOR		3
#define InSignalNum_AUTO		4
#define InSignalNum_REJECT      5
#define InSignalNum_IMMEMG      6
#define InSignalNum_IMOP		7
#define InSignalNum_EEF			8
#define InSignalNum_EEB			9
#define InSignalNum_C1P1		10
#define InSignalNum_C1P2		11
#define InSignalNum_C2P1		12
#define InSignalNum_C2P2		13
#define InSignalNum_MID			14
#define InSignalNum_XALM		15
#define InSignalNum_XCWL		16
#define InSignalNum_XCCWL		17
#define InSignalNum_XORG		18
#define InSignalNum_YALM		19
#define InSignalNum_YCWL		20
#define InSignalNum_YCCWL		21
#define InSignalNum_YORG		22
#define InSignalNum_ZALM		23
#define InSignalNum_ZCWL		24
#define InSignalNum_ZCCWL		25
#define InSignalNum_ZORG		26
#define InSignalNum_AALM		27
#define InSignalNum_ACWL		28
#define InSignalNum_ACCWL		29
#define InSignalNum_AORG		30
#define InSignalNum_BALM		31
#define InSignalNum_BCWL		32
#define InSignalNum_BCCWL		33
#define InSignalNum_BORG		34
#define InSignalNum_CALM		35
#define InSignalNum_CCWL		36
#define InSignalNum_CCCWL		37
#define InSignalNum_CORG		38
#define InSignalNum_XSAFE		39
#define InSignalNum_YSAFE		40
#define InSignalNum_ZSAFE		41
#define InSignalNum_ASAFE		42
#define InSignalNum_BSAFE		43
#define InSignalNum_CSAFE		44
#define InSignalNum_PHOR		45
#define InSignalNum_PVER		46
#define InSignalNum_RHOR		47
#define InSignalNum_RVER		48
#define InSignalNum_RASC		49
#define InSignalNum_RDES		50
#define InSignalNum_RADV		51
#define InSignalNum_RRET		52
#define InSignalNum_OIL			53
#define InSignalNum_LOW			54
#define InSignalNum_KEYRUN	55
#define InSignalNum_KEYSTOP	56
#define InSignalNum_KEYHOME	57
#define InSignalNum_ADVSAFE	58
#define InSignalNum_DESSAFE	59
#define InSignalNum_EMG			60
#define InSignalNum_PWROFF      61
#define InSignalNum_VAC1        62
#define InSignalNum_VAC2        63
#define InSignalNum_GRIP1       64
#define InSignalNum_GRIP2       65
#define InSignalNum_GRIP3       66
#define InSignalNum_GRIP4       67
#define InSignalNum_NotSignal	0xFF

//输出信号编号
#define OutSignalNum_Null		0
#define OutSignalNum_EMO		1
#define OutSignalNum_EMC		2
#define OutSignalNum_MAF		3
#define OutSignalNum_EEF		4
#define OutSignalNum_EEB		5
#define OutSignalNum_ROB		6
#define OutSignalNum_C1P1		7
#define OutSignalNum_C1P2		8
#define OutSignalNum_C2P1		9
#define OutSignalNum_C2P2		10
#define OutSignalNum_HMAF		11
#define OutSignalNum_HEMC		12
#define OutSignalNum_BEEP		13
#define OutSignalNum_ALM		14
#define OutSignalNum_MANLED	15
#define OutSignalNum_AUTOLED	16
#define OutSignalNum_XON		17
#define OutSignalNum_YON		18
#define OutSignalNum_ZON		19
#define OutSignalNum_AON		20
#define OutSignalNum_BON		21
#define OutSignalNum_CON		22
#define OutSignalNum_PHOR		23
#define OutSignalNum_PVER		24
#define OutSignalNum_RHOR		25
#define OutSignalNum_RVER		26
#define OutSignalNum_RASC		27
#define OutSignalNum_RDES		28
#define OutSignalNum_RADV		29
#define OutSignalNum_RRET		30
#define OutSignalNum_RSPEED	31
#define OutSignalNum_OIL		32
#define OutSignalNum_RADJASC	33
#define OutSignalNum_RADJADV	34
#define OutSignalNum_VAC1       35
#define OutSignalNum_VAC2       36
#define OutSignalNum_GRIP1      37
#define OutSignalNum_GRIP2      38
#define OutSignalNum_GRIP3      39
#define OutSignalNum_GRIP4      40
#define OutSignalNum_CONV       45 //传送带
#define OutSignalNum_CUT        46 //剪刀
#define OutSignalNum_STOP       48
#define OutSignalNum_NoSignal	0xFF

#endif
